services:
  redis:
    image: redis:latest
    container_name: maas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: maas_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: maas_jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector HTTP
      - "6831:6831/udp"  # Jaeger agent UDP
      - "4317:4317"  # OTLP gRPC
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data: