@baseUrl = http://localhost:8080
@tokenWithLLM = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc3MzY2NjgzNzkyYzU5YmFmZWQzYjM1IiwiZW1haWwiOiJsbG1AZXhhbXBsZS5jb20iLCJwZXJtaXNzaW9ucyI6eyJHZW5lcmF0ZUxsbU1lbWUiOnRydWV9LCJleHAiOjE3MzU3MTU1NTQsImlhdCI6MTczNTYyOTE1NH0.msCeJvj8QSrQBLZcd8KYyOVE_U95VsiY8vP6WSmX0Uc
@tokenWithoutLLM = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc3MzY2Njc2YTYyYjhiMjg4ZjljOWFmIiwiZW1haWwiOiJub25sbG1AZXhhbXBsZS5jb20iLCJwZXJtaXNzaW9ucyI6eyJHZW5lcmF0ZUxsbU1lbWUiOmZhbHNlfSwiZXhwIjoxNzM1NzE1NTU1LCJpYXQiOjE3MzU2MjkxNTV9.aZvolW4-cEiWqhaEObTLtgdo7mzhMp24tnHw4nWcgNM

### POST request for lngg Island City, NY - No Auth Header
POST {{baseUrl}}/v1/meme
Content-Type: application/json

{
{
  "lat": 40.730610,
  "lng": -73.935242,
  "query": "generate an image with 1000 shoes"
}

### POST request for lngg Island City, NY - Invalid Header
POST {{baseUrl}}/v1/meme
Content-Type: application/json
Authorization: Bearer badtoken

{
  "lat": 40.730610,
  "lng": -73.935242,
  "query": "generate an image with 1000 shoes"
}

### POST request for lngg Island City, NY - Valid Token with llm permissions
POST {{baseUrl}}/v1/meme
Content-Type: application/json
Authorization: Bearer {{tokenWithLLM}}

{
  "lat": 40.730610,
  "lng": -73.935242,
  "query": "generate an image with 1000 shoes"
}

### POST request for Istanbul, Turkey - Valid Token without llm permissions
POST {{baseUrl}}/v1/meme
Content-Type: application/json
Authorization: Bearer {{tokenWithoutLLM}}

{
  "lat": 41.008240,
  "lng": 28.978359,
  "query": "generate an image with turkish coffee"
}

### POST request / Valid Token without llm permissions
POST {{baseUrl}}/
Authorization: Bearer {{tokenWithoutLLM}}

### GET Request to get token balance
GET {{baseUrl}}/v1/tokens
Authorization: Bearer {{tokenWithoutLLM}}
